apiVersion: v1
kind: Namespace
metadata:
  name: test-csi-snapshot
---
kind: Pod
apiVersion: v1
metadata:
 name: my-csi-app
 namespace: test-csi-snapshot
spec:
 containers:
   - name: my-frontend
     image: busybox
     volumeMounts:
     - mountPath: "/data"
       name: my-csi-volume
     command: [ "sleep", "1000000" ]
     command: ["/bin/sh"]
     args: ["-c", "while true; do echo Ping>> /data/out.txt; sleep 300; done"]
 volumes:
   - name: my-csi-volume
     persistentVolumeClaim:
       claimName: csi-pvc
