apiVersion: v1
kind: Namespace
metadata:
  name: test-csi-snapshot
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-pvc
  namespace: test-csi-snapshot
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  storageClassName: longhorn
