kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-snapshot-vsc
  labels:
    velero.io/csi-volumesnapshot-class: "true"  
driver: driver.longhorn.io
deletionPolicy: Retain
parameters:
  type: snap
